version: '3.4'

services:
  booklibrary:
    image: ${DOCKER_REGISTRY-}booklibrary-backend
    build:
      context: ./BackEnd/BookLibrary/
    container_name: booklibrary-backend
    ports:
      - "8080:8081"

  sql-server:
    image: ${DOCKER_REGISTRY-}booklibrary-sql
    build:
      context: ./DB/
    container_name: booklibrary-sql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin123!"
    volumes:
      - ./DB/your_sql_scripts:/usr/src/sql

  react-app:
    image: ${DOCKER_REGISTRY-}booklibrary-frontend
    stdin_open: true
    build:
      context: ./FrontEnd/books-library/
    container_name: booklibrary-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd/books-library/node_modules:/app/node_modules
      - "./FrontEnd/books-library:/app:delegated"
    environment:
      WDS_SOCKET_HOST: "127.0.0.1"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
